from drf_spectacular.utils import extend_schema, OpenApiExample
from get_main_pages.serializers.analise_escritorio.serializer import (
    ResponseSerializer,
    RequestSerializer,
)

ESCRITORIOS_SCHEMA = {
    "tags": ["Completos"],
    "summary": "Análise de atividade de Todos os Escritórios cadastrados no sistema.",
    "description": "Recebe start_date, end_date e api_token e retorna métricas por Escritório.",
    "request": RequestSerializer,
    "responses": {200: ResponseSerializer(many=True)},
    "examples": [
        OpenApiExample(
            "Exemplo de Request",
            value={
                "start_date": "2025-04-01",
                "end_date": "2025-05-28",
                "api_token": "79f7db4785845f5fa117dc3a0951241bc50d2d81841be",
            },
            request_only=True,
        ),
        OpenApiExample(
            "Exemplo de Response",
            value=[
                {
                    "escritorio": "ASSESSORIA EXEMPLO CALDAS LTDA",
                    "codigo": 699,
                    "clientes": {
                        "jan/2024": 543,
                        "fev/2024": 556,
                        "mar/2024": 560,
                        "abr/2024": 571,
                        "mai/2024": 581,
                        "jun/2024": 592,
                        "jul/2024": 597,
                        "ago/2024": 613,
                        "set/2024": 615,
                        "out/2024": 623,
                        "nov/2024": 628,
                        "dez/2024": 634,
                    },
                    "importacoes": {
                        "entradas": {
                            "jan/2024": 18,
                            "fev/2024": 11,
                            "mar/2024": 18,
                            "abr/2024": 10,
                            "mai/2024": 20,
                            "jun/2024": 19,
                            "jul/2024": 6,
                            "ago/2024": 8,
                            "set/2024": 8,
                            "out/2024": 11,
                            "nov/2024": 10,
                            "dez/2024": 11,
                        },
                        "saidas": {
                            "jan/2024": 0,
                            "fev/2024": 0,
                            "mar/2024": 0,
                            "abr/2024": 0,
                            "mai/2024": 0,
                            "jun/2024": 0,
                            "jul/2024": 0,
                            "ago/2024": 0,
                            "set/2024": 0,
                            "out/2024": 0,
                            "nov/2024": 0,
                            "dez/2024": 0,
                        },
                        "servicos": {
                            "jan/2024": 56,
                            "fev/2024": 46,
                            "mar/2024": 119,
                            "abr/2024": 93,
                            "mai/2024": 82,
                            "jun/2024": 77,
                            "jul/2024": 5,
                            "ago/2024": 2,
                            "set/2024": 2,
                            "out/2024": 9,
                            "nov/2024": 4,
                            "dez/2024": 2,
                        },
                        "lancamentos": {
                            "jan/2024": 559,
                            "fev/2024": 370,
                            "mar/2024": 496,
                            "abr/2024": 458,
                            "mai/2024": 448,
                            "jun/2024": 438,
                            "jul/2024": 191,
                            "ago/2024": 176,
                            "set/2024": 143,
                            "out/2024": 266,
                            "nov/2024": 139,
                            "dez/2024": 8,
                        },
                        "lancamentos_manuais": {
                            "jan/2024": 0,
                            "fev/2024": 0,
                            "mar/2024": 0,
                            "abr/2024": 0,
                            "mai/2024": 0,
                            "jun/2024": 0,
                            "jul/2024": 0,
                            "ago/2024": 0,
                            "set/2024": 0,
                            "out/2024": 0,
                            "nov/2024": 0,
                            "dez/2024": 0,
                        },
                        "porcentagem_lancamentos_manuais": {
                            "jan/2024": "0.0%",
                            "fev/2024": "0.0%",
                            "mar/2024": "0.0%",
                            "abr/2024": "0.0%",
                            "mai/2024": "0.0%",
                            "jun/2024": "0.0%",
                            "jul/2024": "0.0%",
                            "ago/2024": "0.0%",
                            "set/2024": "0.0%",
                            "out/2024": "0.0%",
                            "nov/2024": "0.0%",
                            "dez/2024": "0.0%",
                        },
                        "total_entradas": 150,
                        "total_saidas": 0,
                        "total_servicos": 497,
                        "total_lancamentos": 3692,
                        "total_lancamentos_manuais": 0,
                        "total_geral": 4339,
                        "porcentagem_total_lancamentos_manuais": "0.0%",
                    },
                }
            ],
            response_only=True,
            status_codes=["200"],
        ),
    ],
}
