from drf_spectacular.utils import extend_schema, OpenApiExample
from get_empresas.serializers.lista_empresas.serializer import (
    ListaEmpresasRequestSerializer,
    ListaEmpresasResponseSerializer,
)

EMPRESAS_SCHEMA = {
    "tags": ["Empresa"],
    "summary": "Lista de todas as empresas cadastradas no sistema.",
    "description": "Retorna todos os dados de empresas cadastradas no sistema.",
    "request": ListaEmpresasRequestSerializer,
    "responses": {200: ListaEmpresasResponseSerializer},
    "examples": [
        OpenApiExample(
            "Exemplo de Request",
            value={"api_token": "79f7db4785845f5fa117dc3a0951241bc50d2d81841be"},
            request_only=True,
        ),
        OpenApiExample(
            "Exemplo de Response",
            value={
                "Empresas": [
                    {
                        "nome_empresa": "ACME COMÉRCIO LTDA",
                        "CEP": "12345678",
                        "cnpj": "12345678000199",
                        "ramo_atividade": "Comércio",
                        "CNAE": 5123456.0,
                        "CNAE_20": "5123456",
                        "usa_CNAE_20": "S",
                        "codigo_empresa": 10001,
                        "responsavel_legal": "JOÃO SILVA",
                        "situacao": "A",
                        "data_inatividade": "null",
                        "data_cadastro": "2010-05-10",
                        "CAE": 12345.0,
                        "cpf_responsavel": "12345678901",
                        "contador": 1,
                        "email": "contato@acme.com.br",
                        "data_inicio_atividades": "2010-05-10",
                        "duracao_contrato": "I",
                        "data_termino_contrato": "null",
                        "razao_social": "ACME COMÉRCIO LTDA",
                        "motivo_inatividade": 0,
                        "email_resp_legal": "joao.silva@acme.com.br",
                        "cert_digital": "S",
                        "regime_tributario": "Lucro Real",
                    },
                    {
                        "nome_empresa": "INDUSTRIA BETA SA",
                        "CEP": "87654321",
                        "cnpj": "98765432000188",
                        "ramo_atividade": "Indústria",
                        "CNAE": 6543210.0,
                        "CNAE_20": "6543210",
                        "usa_CNAE_20": "N",
                        "codigo_empresa": 10002,
                        "responsavel_legal": "MARIA OLIVEIRA",
                        "situacao": "A",
                        "data_inatividade": "null",
                        "data_cadastro": "2015-09-20",
                        "CAE": 54321.0,
                        "cpf_responsavel": "10987654321",
                        "contador": 2,
                        "email": "contato@betasa.com.br",
                        "data_inicio_atividades": "2015-09-20",
                        "duracao_contrato": "I",
                        "data_termino_contrato": "null",
                        "razao_social": "INDUSTRIA BETA SA",
                        "motivo_inatividade": 0,
                        "email_resp_legal": "null",
                        "cert_digital": "N",
                        "regime_tributario": "Lucro Presumido",
                        "escritorios": [
                            {
                                "codigo_escritorio": 101,
                                "id_cliente_contrato": 5001,
                                "nome_escritorio": "CONTABIL BETA",
                            },
                            {
                                "codigo_escritorio": 102,
                                "id_cliente_contrato": 5002,
                                "nome_escritorio": "ASSESSORIA ALPHA",
                            },
                        ],
                    },
                    {
                        "nome_empresa": "SERVIÇOS GAMMA ME",
                        "CEP": "11223344",
                        "cnpj": "11223344000177",
                        "ramo_atividade": "Serviços",
                        "CNAE": "null",
                        "CNAE_20": "null",
                        "usa_CNAE_20": "S",
                        "codigo_empresa": 10003,
                        "responsavel_legal": "CARLOS PEREIRA",
                        "situacao": "I",
                        "data_inatividade": "2023-03-15",
                        "data_cadastro": "2018-11-11",
                        "CAE": "null",
                        "cpf_responsavel": "22334455678",
                        "contador": 1,
                        "email": "carlos.pereira@gammaserv.com",
                        "data_inicio_atividades": "2018-11-11",
                        "duracao_contrato": "T",
                        "data_termino_contrato": "2023-03-15",
                        "razao_social": "SERVIÇOS GAMMA ME",
                        "motivo_inatividade": 2,
                        "email_resp_legal": "null",
                        "cert_digital": "N",
                        "regime_tributario": "Simples Nacional",
                    },
                ]
            },
            response_only=True,
            status_codes=["200"],
        ),
    ],
}
